-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiVAfd81Kks7nsZaf
cnlyNOMVFfxee7fLRidYjgldhyegCgYIKoZIzj0DAQehRANCAASrpRdm2mFrg4ur
Nofw3fMYVi2RC9ZelZWdY2HopeD5r9kwBq3iABEBiyxbseZNXMAzrmivNJR6yxHM
Er3Zo/vs
-----END PRIVATE KEY-----